### ISSUE TITLE
Error when empty input

### ISSUE THREAD

**Issue by tebanhdez** [crgz/swine#1]
Die result: 5. Enter [D] to roll, or [P] to stand: 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4828)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1555)
	at com.github.crgz.Game.stay(Game.java:94)
	at com.github.crgz.Game.play(Game.java:67)
	at com.github.crgz.Game.play(Game.java:36)
	at com.github.crgz.Game.main(Game.java:126)
	
Simply add a validation before the switch:
```
while (true) {
            System.out.print("Enter [R] to repeat [S] to exit: ");
            String line = nextLine(in);
            switch (line.charAt(0)) {
                case 'R':
                    return true;
                case 'S':
                    return false;
            }
        }

while (true) {
            System.out.print("Enter [R] to repeat [S] to exit: ");
            String line = nextLine(in);
            if(line == null || line.isBlank())
                continue;
            switch (line.charAt(0)) {
                case 'R':
                    return true;
                case 'S':
                    return false;
            }
        }

**Comment by crgz** [comment]
Fixed! Thanks @tebanhdez for helping me to improve my code! :)
